# Generated by Django 5.1.3 on 2024-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=15)),
            ],
        ),
    ]
