# Generated by Django 5.1.1 on 2024-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitsVendors',
            fields=[
                ('vendor_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=60)),
                ('vendor_location', models.CharField(max_length=60)),
            ],
        ),
    ]
