# Generated by Django 5.1.3 on 2024-11-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='fields',
        ),
    ]
